apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-php-pg-helm-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sdurgalaxmi/php-pg-helm.git
    targetRevision: HEAD
    path: php-pg-helm-app
  destination: 
    server: https://kubernetes.default.svc
    namespace: myphppgapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
